Refactoring, etc
arkhn/warehouse-api pull request #138
Opened 2020-09-21 09:20 UTC by vmttn

2020-09-22 16:33 UTC, Jasopaum reviewed
A few general remarks/questions:

- Not every file in data/definitions contains definitions. For instance, valuesets are standard fhir documents, not really definitions. I would rename the folder to something less specific.

- Why did you move everything to a `fhir-api` subfolder?

2020-09-22 16:33 UTC, Jasopaum commented on monstache.toml
> -# connect to MongoDB using the following URL
Why don't we use this conf file in the docker-compose anymore?

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/scripts/initiate_rep_set.sh
> -#!/bin/sh
Where did this move?

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/scripts/upload_bundles.py
> -import sys
Where did all the scripts move? 😅

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/tests/db/db_test.py
> -from db import get_db_connection, get_es_connection, get_store, reset_db_connection, DB_NAME
Did this move somewhere?

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/CONTRIBUTING.md
> +# Contributing to the `fhir-api`
Thanks 😍

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/docker-compose.yml
> +# dotenv file template.
They aren't really documented but I think they're explicit enough 🙂

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/Dockerfile
> +RUN python -m venv ${VIRTUAL_ENV}
Why is this needed?
Would we need to push a virtualenv then?

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/Dockerfile
> +RUN pip install --no-cache-dir --upgrade pip uwsgi
Why is this not in the requirements file?

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
Is all the cleaning needed is we don't use this one as the final image?

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/docker-entrypoint.sh
> +#!/bin/bash
Is this file automatically detected by docker?

2020-09-22 16:33 UTC, Jasopaum commented on fhir-api/fhir_api/app.py
> +    SRC_DIR is a path to the definitions directory.
nit: SRC_DIR -> src_dir

2020-09-22 16:33 UTC, Jasopaum commented on elasticsearch.yml
> -node:
Has this moved somewhere?

2020-09-22 16:56 UTC, simonvadee requested changes

2020-09-22 16:56 UTC, simonvadee commented on .github/workflows/main.yml
> +          labels: |
what's all this ?

2020-09-22 16:56 UTC, simonvadee commented on .github/workflows/main.yml
> +      - uses: docker/login-action@v1
nice

2020-09-22 16:56 UTC, simonvadee commented on .github/workflows/main.yml
> +          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
is this the branch name ? the commit hash ?

2020-09-22 16:56 UTC, simonvadee commented on CODEOWNERS
> +* @vmttn
🦾

2020-09-22 16:56 UTC, simonvadee commented on fhir-api/CONTRIBUTING.md
> +# Contributing to the `fhir-api`
❤️

2020-09-22 16:56 UTC, simonvadee commented on fhir-api/docker-compose.yml
> +    image: rwynn/monstache:6.7.0
actually we need our own monstache image arkhn/monstache:6.6.0 because we use a custom plugin for it (see deployment `docker-compose.elastic.yml.j2`)

2020-09-22 16:56 UTC, simonvadee commented on fhir-api/docker-compose.yml
> +      - MONSTACHE_DIRECT_READ_NS=fhirstore.Patient
not relevant anymore (with our own image of monstache), we can talk about this at the office

2020-09-22 16:56 UTC, simonvadee commented on fhir-api/docker-compose.yml
> +    image: rwynn/monstache:6.7.0
also, it's missing the config file

2020-09-23 07:53 UTC, vmttn commented on fhir-api/Dockerfile
> +COPY --chown=uwsgi:uwsgi tests /srv/tests
* Running the tests closer to the production runtime is safer. For instance, in local dev, running them in an isolated new environment with tox. Here we take things a little further.
* The environment setup logic is already implemented in the `Dockerfile` (e.g. installing os dependencies such as gcc etc.).

2020-09-23 08:07 UTC, vmttn commented on CODEOWNERS
> +* @simonvadee
* We can definitely put teams here ! But it would be nice to have different teams for the back and the front, since its a monorepo.
* I think its a good way of documenting who's in charge of reviewing PRs and to [assign automatically PRs.](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#about-code-owners).
* Above all else, the purpose of this file is to automated stuff and save some time. Sure its a tradeoff, but I dont feel like its a lot to maintain :) (only the reviewers would be in this file)

2020-09-23 08:08 UTC, vmttn commented on fhir-api/.gitignore
> +# TODO(vmttn): uncomment next line
oups :blush:

2020-09-23 08:17 UTC, vmttn commented on fhir-api/Dockerfile
> +RUN pip install --no-cache-dir --upgrade pip uwsgi
* `uwsgi` ? It is in the `requirements/base.txt`.
* Installing `uwsgi` separately beforehand is just a trick to use the cache. Really is just optimization, can be removed if you'd rather.

2020-09-23 08:18 UTC, vmttn commented on fhir-api/Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
Its not the final image, but it will be on your disk still.

2020-09-23 08:20 UTC, vmttn commented on fhir-api/docker-entrypoint.sh
> +#!/bin/bash
What to do you mean ? It's conventional to name the entrypoint `docker-entrypoint.sh`, but I can't say if thats leverage by docker.

2020-09-23 08:26 UTC, vmttn commented on fhir-api/fhir_api/app.py
> +    SRC_DIR is a path to the definitions directory.
(nit ? :) )

The `click` module will show the argument in caps (since it is a positional argument). I put SRC_DIR in caps to match it :

```bash
~/Arkhn/warehouse-api/fhir-api $ flask load-defs --help
Usage: flask load-defs [OPTIONS] SRC_DIR

  Load FHIR definitions.

  SRC_DIR is a path to the definitions directory.

Options:
  --help  Show this message and exit.
```

2020-09-23 08:50 UTC, vmttn commented on fhir-api/fhir2ecrf/__init__.py
> -from fhir2ecrf.fhir2ecrf import FHIR2eCRF  # noqa
I agree with you, shortcutting the pathname location can improve readability when you import stuff. For instance, when we have:

```python
from package.subpackage.module_a import A
from package.subpackage.module_b import B
```
then
```python
from package.subpackage import A, B
```
is much cleaner.

Given that, I removed the shortcutting because :
1. It is only `from package.subpackage.module import FHIR2eCRF`.
2. It is imported only once (in `api.py`) and the import is even commented out (in `master`)

2020-09-23 09:43 UTC, vmttn commented on monstache.toml
> -# connect to MongoDB using the following URL
We don's use the conf, but we use environment variables instead (check the compose file).

Using env vars over conf files has several advantages:

* Deploying
  * conf files: require either to copy the files in a new dockerfile (e.g. a dockerfile extending monstache) or to mount a volume at runtime. Later is more flexible, but requires to make the files available (e.g. with ansible)
  * env vars: inject variables.
* Modifying the conf (e.g. for local development)
  * conf files: modify several files, which will show as changes in local git repo, with duplicated information that needs to match between files.
  * env vars: modify one `.env` file, which is ignored in repo. Variable substitution can be used in orchestrator conf file to stay DRY.
* Security
  * conf files: are not ignored, so sensitive information can (and will eventually) be pushed on github
  * env vars: will not be on github
* Checking configuration in running container
  * conf files: we need to know what file to look for and where.
  * env vars: configuration, for **any** container, can simply be checked with `docker exec -it <container_name> env`
* Maintainability:
  * conf files: several files, with duplicated information
  * env vars: less files around, just a sample `.template.env`

Plus, with env vars, we can easily move from the development server to a containerized (locally) server.

2020-09-23 09:44 UTC, vmttn commented on elasticsearch.yml
> -node:
Same as https://github.com/arkhn/warehouse-api/pull/138#discussion_r492855802

2020-09-23 09:50 UTC, vmttn commented on .github/workflows/main.yml
> +          labels: |
This GA (maintained by docker) use [BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/) as a image build backend. It has more features, hence additional configuration.

Check out the doc : https://github.com/docker/build-push-action#inputs

2020-09-23 09:56 UTC, vmttn commented on .github/workflows/main.yml
> +          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
The builded image will have 2 or 3 tags:
* `arkhn/fhir-api:<first 8 symbol of commit hash>`
* `arkhn/fhir-api:<branch name with "/" replaced by "-" >`
* `arkhn/fhir-api:latest` if on master

2020-09-23 09:58 UTC, simonvadee commented on fhir-api/docker-entrypoint.sh
> +#!/bin/bash
@Jasopaum it's not automatic, here's the dockerfile:
```dockerfile
...
COPY --chown=uwsgi:uwsgi ["capabilities.json", "docker-entrypoint.sh", "uwsgi.ini", "/srv/"]
...
RUN chmod +x docker-entrypoint.sh
ENTRYPOINT ["/srv/docker-entrypoint.sh"]
```

2020-09-23 10:00 UTC, simonvadee commented on fhir-api/fhir_api/app.py
> +    SRC_DIR is a path to the definitions directory.
nit is short for "nit-picking" https://stackoverflow.com/questions/27810522/what-does-nit-mean-in-hacker-speak

2020-09-23 10:51 UTC, simonvadee commented on .github/workflows/main.yml
> +          labels: |
cool thanks

2020-09-23 10:55 UTC, simonvadee commented on .github/workflows/main.yml
> +          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
ok got it!
I think that tagging with the commit hash (at least its first symbols) is useful in many cases (I used it 2 days ago when I had to re-deploy a specific version of a service in an environment that required it)

2020-09-23 13:38 UTC, Jasopaum commented on fhir-api/fhir2ecrf/__init__.py
> -from fhir2ecrf.fhir2ecrf import FHIR2eCRF  # noqa
Fine by me, we'll put that back later if needed 👍

2020-09-23 13:42 UTC, Jasopaum commented on fhir-api/docker-entrypoint.sh
> +#!/bin/bash
☝️ That's what I missed

2020-09-23 13:43 UTC, Jasopaum commented on fhir-api/docker-entrypoint.sh
> +flask load-defs /var/data/definitions
Does it try to insert the fhir resource each time the docker is restarted?
I think that's already what we had before but do you think there a way to avoid that?

2020-09-23 14:31 UTC, vmttn reviewed
@Jasopaum 

## 1

> * Not every file in data/definitions contains definitions. For instance, valuesets are standard fhir documents, not really definitions. I would rename the folder to something less specific.

In the [FHIR specification downloading page](https://www.hl7.org/fhir/downloads.html), these files are refered to as *FHIR definitions*

The term *Bundle* refers to the data model used to store these definitions. I think an analogy in python would be to name a list of names `array` rather than `names`. What do you think ?

| | |
-- | --
**FHIR Definitions** | **All the value sets, profiles, etc. defined as part of the FHIR specification,** and the included implementation guides:               XML        JSON        Forge: Special version of definitions for Forge  (temporary)              This is the master set of definitions that should be the first  choice whenever generating any implementation artifacts. All       the other forms below include only subsets of the information  available in these **definition files**, and do not contain all of the rules  about what makes resources valid. Implementers       will still need to be familiar with the content of the  specification and with any profiles that apply to the resources in order to make a conformant implementation.

## 2

>     * Why did you move everything to a `fhir-api` subfolder?

I moved (almost) everything related to python/backend stuff to the `fhir-api` subfolder. `fhir-api` and `front` could very well lived in 2 different repositories (since we have a headless backend and a dedicated web app). Though I am all in favor of a monorepo to keep the front and the back synchronized (its a real burden). Here is why I would rather have things clearly separated though:

* It is clearer for the newcomers
* We avoid nameclashing between files (directories act as namespaces)
* If I am working on the back, I dont want the IDE to index front code (and vice versa). I just open the `fhir-api` folder in my IDE

2020-10-21 09:53 UTC, vmttn commented on fhir-api/docker-compose.yml
> +    image: rwynn/monstache:6.7.0
Done

2020-10-21 10:22 UTC, simonvadee approved these changes
💥

2020-10-21 10:25 UTC, merged