Refactor fhir-api start-up
arkhn/warehouse-api pull request #176
Opened 2020-11-12 16:07 UTC by simonvadee

## Fixes
Fixes #175  by @simonvadee 

## Description

- initiate tjhe mongoDB replica set directly from python code instead of relying on an external command.
- do not try to bootstrap the store everytime fhir-api is started. `flask bootstrap` is now a command available to create mongo collections and ES indices. It should be run from an other container before fhir-api HTTP server is started.
- flask load-defs has been removed from docker entrypoint. It must be run from a different container by overriding the entrypoint (see docker-compose.yml)

2020-11-12 19:23 UTC, Jasopaum approved these changes
lgtm

2020-11-16 09:18 UTC, vmttn requested changes

2020-11-16 09:18 UTC, vmttn commented on fhir-api/fhir_api/db.py
> +        except pymongo.errors.OperationFailure:
`OperationFailure` looks kind of broad.

2020-11-16 09:18 UTC, vmttn commented on fhir-api/docker-compose.yml
> +    hostname: mongo
Have you experienced issues without this (in development) ?
If so can you ad a comment that says why its required in this context.

2020-11-16 09:18 UTC, vmttn commented on fhir-api/docker-compose.yml
> +    restart: on-failure
Why did you set this to `on-failure` ?
I can think of a good reason to do this (to prevent the container to start on reboot). But then I don't understand why you didn't do the same for every services in this file.

2020-11-16 09:18 UTC, vmttn commented on fhir-api/Dockerfile
> +ENV FLASK_APP fhir_api/app
:+1: for never changing variables

2020-11-16 09:18 UTC, vmttn commented on fhir-api/fhir_api/db.py
> +        except pymongo.errors.OperationFailure:
I'm not sure we want to do it behind the scenes in application code.

2020-11-16 09:30 UTC, simonvadee commented on fhir-api/docker-compose.yml
> +    restart: on-failure
you're right I should have used the same rule for all services. done. (Initially I used this policy for api-bootstrap and api-load-defs but it makes sense to extend it to all services).

2020-11-16 09:30 UTC, simonvadee commented on fhir-api/docker-compose.yml
> +    hostname: mongo
since there are no volumes here this is useless. removed.

2020-11-23 13:08 UTC, merged